site_name: DueWiz Dev
theme: flatly
repo_url: https://github.com/DueWiz/Student_Organizer
extra_css:
    - css/highlight.css
    - css/pre.css
pages:
    - Home: index.md
    - Front End:
        - 'Background': 'front-end/background.md'
    - Miscellaneous:
        - 'Tips': 'miscellaneous/tips.md'
    - About: about.md
